### ISSUE TITLE
readdirplus: entry with attributes_follow = 0

### ISSUE THREAD

**Issue by doktorstick** [sahlberg/libnfs#115]
If you have a server that returns the filenames in a readdirplus call, but does not return the attributes, then libnfs presents the file's attributes as all 0's. Instead, it should to do a followup GETATTR on the offending entry(-ies).

**Comment by sahlberg** [comment]
Hi,

I have seen servers that does not support READDIRPLUS at all and there I
fallback to old READDIR (that contains no attributes)
and a GETATTR loop to fetch the attributes them self. This is currently
triggered only for the case where the server responds with an RPC FUNCRION
NOT SUPPORTED error.

Only time I have seen a server return all zero attributes for READDIRPLUS
is when there is another subvolume mounted ontop of it.


It should not be too horrible to solve this.
Can you collect a network trace to share with me so I can see exactly how
the reply from the server looks like.
The easiest solution here might be if I can detect this situation from the
reply so I can trigger the fallback for "bad" servers that I already have
for broken READDIRPLUS.



I am curious. What is the exact type of NFS server you use? As I said I
have not seen this before so I am a very curious :-)

**Comment by doktorstick** [comment]
I'll see what I can do. The NetApp filer contains confidential information and is not under my control (i.e., I may not be able to setup a "safe" reproducible environment.)

I will say that examining various directories entries in the pcap, many have different ```fattr3.fsid```, but this may be an artifact of how NetApp manages things.

**Comment by sahlberg** [comment]
It is really just the readdirplus reply I am interested in.

Maybe you can print it as ASCII using tshark   and then edit and remove the
file-names themself
and thus remove any sensitive data.

**Comment by doktorstick** [comment]
```$ tshark -r ffstat-rewrite.pcap -V -O rpc,nfs | obfus.py > ffstat-rewrite-obfus.txt```

This has the mounting, RD+s, and LOOKUPs for one directory. I rewrote network info and substituted the filenames with a consistent mapping (i.e., file0005 is the same file everywhere file0005 is seen). You can grab it here: https://dl.dropboxusercontent.com/u/12952897/Bug/ffstat-rewrite-obfus.txt

**Comment by sahlberg** [comment]
Can you test this branch :   readdirplus-weird-server-fix
I started working on triggering a fallback to READDIRPLUS based on whether
the reply contains entries without any attributes.

I think the approach for this patch is not workable for a solution in
"master" since I start realizing that there are several problems with the
approach.
However, it is still valuable as a test to check that using LOOKUP on these
"files" will work, which is still uncertain.


Is there something unusual about these files? such are they some kind of
snapshots or similar?


The only times I have seen an NFS server return null attributes for a
directory entry is in the case where the entry is a mountpoint on the
server on which a different filesystem is mounted.
For example if a server exports both /export/data and
/export/data/other-filesystem and these are two different filesystems.
For that case when you would try a READDIRPLUS of data   or if you would
try a LOOKUP of /export/data/other-filesystem, then the server would
normally
return an entry without any attributes.
(Reason for this is because the protocol does not allow an NFS operation to
start in one filesystem and return a filehandle for a file in a different
filesystem.
This is also the reason why for these cases a normal nfs client would have
to mount BOTH filesystems from the server).


So, please try this branch and see if you can see the file attributes. If
that works then I can try to come up with a proper solution to drive the
failback to a LOOKUP loop.

**Comment by doktorstick** [comment]
I'm being told that it is not an overlapping mount; I also issued a ```showmount -e $serverip``` and it returns one mountpoint: ```/ (everyone)```. I'm hoping to get to tryout your branch today, tomorrow at the outside.

**Comment by sahlberg** [comment]
Ok,   Also if you could do a 'stat <filename>'   on each of the files
without attributes from a command line prompt when mounting it with the
kernel nfs client.
And the same 'stat <output>' from a few files that does have attributes as
well as for the parent directory.

**Comment by doktorstick** [comment]
I believe your instinct is correct. After reading about server exports in the NFS Illustrated book, checking the filesystem in question, I notice that it does change ```fsid```. In this case:
```
fsid=AA /
fsid=BB /foo/
fsid=CC /bar/
```
I made a small program to ```readdir``` on a specified directory. Grep'ing the ```tshark``` output--for reference, there are 2147 objects inside of ```/```:
```
root# grep attributes_follow rd.tshark | sort | uniq -c
     39             attributes_follow: no value (0)
      2         attributes_follow: no value (0)
      2             attributes_follow: value follows (1)
   4348         attributes_follow: value follows (1)
```
Keep in mind, this is using your test branch you pointed me at. I didn't validate the data I'm getting back is correct with your test code, however.

The simple code isn't much more complicated than:
```
  nfs_opendir (nfs, "/foo", &nfsdir);
  // snip readdir loop
  nfs_closedir (nfs, nfsdir);
```
Okay, so I went back to the ```libnfs``` code base I'm using, which is a few version back and tried the simple test code:
```
root# grep attributes_follow rd-old.tshark | sort | uniq -c
   2145             attributes_follow: no value (0)
      2             attributes_follow: value follows (1)
     53         attributes_follow: value follows (1)
```
Sure enough, there's what I expect.

When looking at what the linux client is doing it does:
```
$ mount -t nfs ...
$ stat ~/mnt/foo
Network File System, FSINFO Call DH: 0xb8c81e4f
Network File System, FSINFO Reply
Network File System, PATHCONF Call DH: 0xb8c81e4f
Network File System, PATHCONF Reply
Network File System, FSINFO Call DH: 0xb8c81e4f
Network File System, FSINFO Reply
Network File System, ACCESS Call, FH: 0xb8c81e4f, [Check: RD LU MD XT DL]
Network File System, ACCESS Reply, [Access Denied: MD XT DL], [Allowed: RD LU]
Network File System, LOOKUP Call DH: 0xb8c81e4f/foo
Network File System, LOOKUP Reply FH: 0x26b49599
```
And then on a file inside of ```foo```:
```
$ stat ~/mnt/foo/.
Network File System, LOOKUP Call DH: 0xb8c81e4f/foo
Network File System, LOOKUP Reply FH: 0x26b49599
Network File System, FSINFO Call DH: 0x26b49599
Network File System, FSINFO Reply
Network File System, PATHCONF Call DH: 0x26b49599
Network File System, PATHCONF Reply
Network File System, FSINFO Call DH: 0x26b49599
Network File System, FSINFO Reply
Network File System, ACCESS Call, FH: 0x26b49599, [Check: RD LU MD XT DL]
Network File System, ACCESS Reply, [Allowed: RD LU MD XT DL]
```
To me this tells me that the client noticed that the ```fsid``` was different, so it had to do a subsequent ```FSINFO``` to track that filesystem.

**Comment by doktorstick** [comment]
You can also cause the "no attributes" without needing other `fsid`'d filesystems.
```
notroot@filer:/exports/test2/a/b$ ls -la .
total 12
drwxrwxr-x 3 notroot notroot 4096 May 11 22:51 .
drwxrwxr-x 3 notroot notroot 4096 May 11 22:51 ..
dr-------- 3 notroot notroot 4096 May 12 00:22 c
notroot@filer:/exports/test2/a/b$ ls -la c
ls: cannot access c/d: Permission denied
ls: cannot access c/c.1: Permission denied
ls: cannot access c/c.2: Permission denied
ls: cannot access c/.: Permission denied
ls: cannot access c/..: Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
-????????? ? ? ? ?            ? c.1
-????????? ? ? ? ?            ? c.2
d????????? ? ? ? ?            ? d
notroot@filer:/exports/test2/a/b$
```

**Comment by sahlberg** [comment]
Sorry but I completely forgot about this.


I have reworked it completely so that I now conditionaly use LOOKUPs for
those entrues where we do not get any attributes.

Please test this branch :
readdirplos-lookup

Once it is good I will merge it to master and release a new version.

Best regards
ronnie sahlberg

**Comment by doktorstick** [comment]
It appears to be working properly. My observation was that it performed the READDIRPLUS as normal, and then sent a bunch of LOOKUPs out back-to-back and the collected the results.

I had only one entry (of 2043) that the LOOKUP did not fill in, and that was because of a NFS3ERR_ACCESS on the LOOKUP.

I call it success. Once it is in the main branch, I'll end up running it through its paces across other filers/mounts, too.

**Comment by sahlberg** [comment]
Thanks for verifying it.

I merged it into master so it will be part of the next release.
