### ISSUE TITLE
NFS3ERR_JUKEBOX(-11)

### ISSUE THREAD

**Issue by keeely** [sahlberg/libnfs#164]
Full error:  Stat call failed with: "NFS: lookup of /mydir failed with NFS3ERR_JUKEBOX(-11)

I got the above error using libnfs to talk to a NAS box.  That was from a nfs_stat64() call, but most of the other calls do it as well.  I can connect, I can chdir("/"), but pretty much all other commands give the above error.

There is nothing wrong with my NAS that I can see, I have another Linux client talking to it fine.  Also my client code works with a 'normal' Linux NFS share.

**Comment by sahlberg** [comment]
Jukebox is an unusual error code for stat().
It usually happens for read() on first read for a file that has been
migrated offline in tiered storage.
I guess it can also happen for stat() if the server also migrates the
inodes themselves offline. Unusual since the inodes are usually so small so
there is little gain by migrating them, but I guess that is what happens
here.


The Jukebox error basically means that the data is not available due to
currently being offline and that the client/app should re-try the command a
little while later.
libnfs will map this to -EAGAIN so what you should do is check if the
command returned -EAGAIN. if it did then wait a little while and then try
the operation again.

**Comment by keeely** [comment]
Hi Ronnie,

Perhaps worth pointing out that I am running libnfs on a Windows machine.

Retrying (at least at the sync interface level with further nfs_stat64() calls) leads to the same value being returned repeatedly, so waiting doesn't help.  Interestingly the only call that returns without error is nfs_stat64("/"), i.e. the root.

nfsstat -m on the working Linux (2.6.32) client says:
rw,relatime,vers=3,rsize=65536,wsize=65536,namelen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=<ip>,mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=<ip>

So perhaps the linux client sends something to kick the NAS into getting the volume online?  There are too many packets on a mount for me to easily decipher what it's doing via tcpdump though.

**Comment by sahlberg** [comment]
On Fri, Jan 20, 2017 at 10:31 AM, keeely <notifications@github.com> wrote:

> Hi Ronnie,
>
> Perhaps worth pointing out that I am running libnfs on a Windows machine.
>
> Retrying (at least at the sync interface level with further nfs_stat64()
> calls) leads to the same value being returned repeatedly, so waiting
> doesn't help. Interestingly the only call that returns without error is
> nfs_stat64("/"), i.e. the root.
>
> nfsstat -m on the working Linux (2.6.32) client says:
> rw,relatime,vers=3,rsize=65536,wsize=65536,namelen=255,hard,
> proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=,mountvers=
> 3,mountport=635,mountproto=udp,local_lock=none,addr=
>
> So perhaps the linux client sends something to kick the NAS into getting
> the volume online? There are too many packets on a mount for me to easily
> decipher what it's doing via tcpdump though.
>
I don't know if this is still the case, but have no reason to think it has
changed,
when the linux client receives a jukebox error it would set a timer and
re-send the command after 5 seconds.
It would then re-send the command every 5 seconds indefinitely until it
receives not-jukebox.

**Comment by keeely** [comment]
Definitely no jukebox error on the Linux client, according to the packet dump.  

When comparing working (Linux) vs non-working (libnfs) dumps the first thing I noticed was that the name field of the credentials section of the RPC requests contains 'libnfs', whereas on Linux it's the DNS name of the machine.  Although those requests appear to still be accepted.  Still, might be worth aligning this with the Linux implementation for cosmetic reasons and to help remove it from future fault-finding.

The other thing I noticed is libnfs does:
FSINFO -> GETATTR -> LOOKUP.

Linux on a mount does:
FSINFO -> PATHCONF -> FSINFO -> ACCESS -> GETATTR -> READDIRPLUS

So perhaps PATHCONF or ACCESS is making the difference.

I only checked the first FSINFO content in detail between the two, but they appear to be identical.

**Comment by keeely** [comment]
Bingo.  Change default Windows uid and gid to zero and everything starts working.  Who'd have believed a NAS could be so broken.  Please consider making this change: s/65534/0/.

**Comment by sahlberg** [comment]
Good work.

Can you also try using the URL arguments to see if you can get this to work
too without using the patch?
By adding ?uid=0&gid=0   to the end of the nfs:// URL you can control what
uid/gid that libnfs will use.

Since this seems to be a permissions issue and not a "file is offline"
issue, the nfs server should return EPERM and not EJUKEBOX.
If possible, if you can make netapp aware that they send the wrong error
code for this, maybe they can fix the error code.


I am hesitant to apply your patch yet, before we try some more things out.
I do not doubt that the patch work but I am not sure this is the right
thing to do.
65534 as the default uid/gid were picked as this is the common "nobody"
user/group in unix and nfs.
Since we do not have a proper uid/gid under windows or android this is a
good uid/gid to have as default just as an indication to the server
that "I don't really know my/have a real uid/gid".


Using 65534 from a windows host to nfs server does work in general. This is
what the windows version of kodi.

I think there might be either an ACL or configuration on your nfs server
that causes this.
I have not worked with netapp boxes in a while and do not have any
documentation in front of me,
but does it have, and could you have activated, some special treatment of
the "nobody" user ?

**Comment by keeely** [comment]
It's old NAS hardware, I very much doubt they will be interested in a bug report.  It may well be a misconfiguration, but since I don't own the device (it's another department) I can't really play with it much.  I'm 100% OK with you not applying my patch, and I understand the 'nobody', particularly if other options might break Kodi.  My thinking was that most people playing with this will be comparing behaviour with Linux mount, which will (I believe) always set uid and gid to zero.  Of course, if they access files as other users it may not be like that.  Also I use Kodi, so I don't want it broken either :-).

**Comment by sahlberg** [comment]
On Wed, Jan 25, 2017 at 1:41 AM, keeely <notifications@github.com> wrote:

> It's old NAS hardware, I very much doubt they will be interested in a bug
> report.
>

Fair enough.


> It may well be a misconfiguration, but since I don't own the device (it's
> another department) I can't really play with it much. I'm 100% OK with you
> not applying my patch, and I understand the 'nobody', particularly if other
> options might break Kodi. My thinking was that most people playing with
> this will be comparing behaviour with Linux mount, which will (I believe)
> always set uid and gid to zero.
>

Linux mounts will set uid/gid to the uid/gid of the current user that is
accessing the file. Libnfs does the same on linux.
But as windows does not have getuid() nor the concept of a unix uid I have
to set it to something and "nobody" is as good as anything else.

Changing to defaulting to the root user might cause other issues as well.
It is reasobably common that NFS servers completely disallow
access for root. On linux this is done by the "root_squash" option in the
exports file.
This causes the server itself to re-map uid 0 to uid 65534 and is fairly
common as a default option.

This is why I am hesitant.



Can you try adding ?uid=0&gid=0   to the NFS URL ?
I.e.   nfs://1.2.3.4/path/to/export?uid=0&gid=0

This should do the same thing and make libnfs use uid 0  when talking to
the server but without changing the default in the code.

**Comment by keeely** [comment]
OK, was only using nfs_mount up to now, hadn't noticed the other API.  Will rework my code to use the other one so I don't have to change my copy of libnfs.  It won't be soon, but I'll test it and report back.

**Comment by keeely** [comment]
Can you please post an example of code that uses the nfs:// notation (couldn't see any examples doing it), so I can try the code out?

**Comment by sahlberg** [comment]
For example utils/nfs-ls.c

The  nfs_parse_url*() functions are used to parse nfs:// style URLs.
If the url contains certain arguments, such as uid=<number>, then they will
update the nfs context to
use that uid value instead of the default.

These arguments are all set from libnfs.c:nfs_set_context_args()

If you don't want to use the url parsing functions, you can set the uid/gid
that libnfs will use by calling the setters directly :

rpc_set_uid(nfs_get_rpc_context(nfs), atoi(val));
        rpc_set_gid(nfs_get_rpc_context(nfs), atoi(val));

All my apps take a nfs url on the command line, thus making the use of url
style arguments such as ?uid=0&gid=0
very convenient.

**Comment by keeely** [comment]
OK, I hadn't looked much at the examples.  Doesn't help I have my own vs2008 port (source is the same but independent project files) and I never bothered compiling the examples :-/.  I've created a hand-crafted python 2.7 wrapper because I couldn't get the existing wrapper to work under Windows: another complication!

So... I'd need to add rpc_set_?id to the DEF file, is that the idea?  I can see now what you meant, unfortunately the nfs_parse_url, just adds complication for me.  I only want to set the values direct, however the necessary functions appear to be declared in libnfs-private.h, which is presumably not supposed to be used by me?

By the way, it looks as though rpc_set_uid_gid might leak an auth structure, although it's obviously not too serious.  In fact, I was about to rip that out and put it in my code directly, then I thought perhaps I should ask if you have any future plans to change the interface.

**Comment by sahlberg** [comment]
On Mon, Jan 30, 2017 at 9:23 AM, keeely <notifications@github.com> wrote:

> OK, I hadn't looked much at the examples. Doesn't help I have my own
> vs2008 port (source is the same but independent project files) and I never
> bothered compiling the examples :-/. I've created a hand-crafted python 2.7
> wrapper because I couldn't get the existing wrapper to work under Windows:
> another complication!
>
> So... I'd need to add rpc_set_?id to the DEF file, is that the idea? I can
> see now what you meant, unfortunately the nfs_parse_url, just adds
> complication for me. I only want to set the values direct, however the
> necessary functions appear to be declared in libnfs-private.h, which is
> presumably not supposed to be used by me?
>
I see. These functions should be made public.
I have fixed this now in the latest commit.




> By the way, it looks as though rpc_set_uid_gid might leak an auth
> structure, although it's obviously not too serious. In fact, I was about to
> rip that out and put it in my code directly, then I thought perhaps I
> should ask if you have any future plans to change the interface.
>
Can you open a separate issue for this?

I have no plans myself for changing it, other than that it would be nice at
some stage to add kerberos support.

I am open to discuss changing these interfaces if you have a usecase that
needs it.

**Comment by sahlberg** [comment]
I have made rpc_get_{g|u}id() public functions so you can easily override the uid/gid from your application.

Closing as solved.
(please open another issue if you want some additional api changes as discussed)
