### ISSUE TITLE
nfs over ssh with fuse: use internal buffers in stead of fd

### ISSUE THREAD

**Issue by stefbon** [sahlberg/libnfs#172]
Hi,

I have  an application which offers access to remote shared folders to users using fuse. Already working are sftp (with my own ssh libraries) and nfs using the systemcommand mount.nfs. (this is of course not fuse). Now I want to provide access to an exported map using libnfs and fuse. I also am considering nfs over ssh. A ssh session to the server is already present, a new direct-tcpip channel is possible. Now libnfs uses a socket, cause it's assuming it has to create the connection to the server. Now I wonder it's possible to use the internal buffers instead of a socket. This socket looks a bit unnecessary, when data arrives in my application, is decoded and integrity checks are done, the payload is ready to be processed by libnfs in stead of sending it to the local socket libnfs listens to. Do you maybe know this is possible? Functions like rpc_read_from_socket need an equivalent like rpc_read_from_buffer.

Thanks in advance,

Stef Bon

**Comment by sahlberg** [comment]
On Wed, Feb 22, 2017 at 11:48 AM, stefbon <notifications@github.com> wrote:

> Hi,
>
> I have an application which offers access to remote shared folders to
> users using fuse. Already working are sftp (with my own ssh libraries) and
> nfs using the systemcommand mount.nfs. (this is of course not fuse). Now I
> want to provide access to an exported map using libnfs and fuse. I also am
> considering nfs over ssh. A ssh session to the server is already present, a
> new direct-tcpip channel is possible. Now libnfs uses a socket, cause it's
> assuming it has to create the connection to the server. Now I wonder it's
> possible to use the internal buffers instead of a socket. This socket looks
> a bit unnecessary, when data arrives in my application, is decoded and
> integrity checks are done, the payload is ready to be processed by libnfs
> in stead of sending it to the local socket libnfs listens to. Do you maybe
> know this is possible? Functions like rpc_read_from_socket need an
> equivalent read from a buffer like rpc_read_from_buffer.
>

It would be possible, but it would be a lot more work.
For NFS it is not sufficient with just a single TCP session. During mount
you need 4 different TCP sessions.

1, TCP connection to port 111 on the server. This is portmapper service and
it is used to query which port MOUNT daemon is available on.
2, TCP connection to ephemeral port for MOUNT daemon. This is used to
acquire the filehandle for the root of the share.
3, TCP to portmapper again to discover the port for NFS daemon
4, TCP connection to NFS. This is almost always port 2049.


I suspect a much easier approach is if you use LD_PRELOAD and override
socket()/bind()/connect()/send()/... and change them to
emulate what libnfs expects.
I.e. create wrapper functions that look like a socket but just a wrapper to
pass the data to something that does port forwarding to the other end of
the ssh connection.

**Comment by stefbon** [comment]
Ok. For me it's confusing. Sollutions I've found like:

https://gist.github.com/proudlygeek/5721498

just forward the tcp port for NFS. There are a lot of those suggestions. But these use the kernel nfs client module. Does this work different?

Stef Bon

**Comment by sahlberg** [comment]
On Mon, Feb 27, 2017 at 3:01 AM, stefbon <notifications@github.com> wrote:

> Ok. For me it's confusing. Sollutions I've found like:
>
> https://gist.github.com/proudlygeek/5721498
>
> just forward the tcp port for NFS. There are a lot of those suggestions.
> But these use the kernel nfs client module. Does this work different?
>

Good find but that only works for NFSv4 while libnfs and the fuse module
only supports NFSv3.

You should be able to do something similar though.
There are three ports involved in NFSv3 so you need to port-forward all
three:

1,  localhost:111 -> remote:111
This is the port for portmapper.  Libnfs talks to this port to discover
which port to use to talk to the other services.
Port 111 is hardcoded in NFS/ONC-RPC

2,  localhost:nfs -> remote:nfs
This is almost always running on port 2049 and is the core nfs service.
Use rpcinfo and point it to the server to verify. NFS runs on rpc program
100003, version 3.

Libnfs uses a built in portmapper client to discover which port it should
connect to,
so you need to forward the same port locally to the same port remotely.

3, localhost:mount -> remote:mount
There is no standard port for Mount daemon and it usually runs on a random
ephemeral port.
Again, use rpcinfo pointed to the server to find out which port it runs to
and set up the port forwarding
accordingly.

The program number for mount daemon is 100005



If you want to avoid spawning off a child process to run rpcinfo, then
libnfs does come with a built-in
portmapper client you could use from your app to discover the ports for
mount and nfs.
There should be examples for portmapper client in the examples subdirectory.

**Comment by stefbon** [comment]
>Good find but that only works for NFSv4 while libnfs and the fuse module
>only supports NFSv3.

I think there is a misunderstanding. I want to develop my own fuse fs for nfs4. I've already written a fuse module for sftp.

I've seen the example nfs4-cat.c to follow.

Stef

**Comment by sahlberg** [comment]
On Tue, Feb 28, 2017 at 5:17 AM, stefbon <notifications@github.com> wrote:

> Good find but that only works for NFSv4 while libnfs and the fuse module
> only supports NFSv3.
>
> I think there is a misunderstanding. I want to develop my own fuse fs for
> nfs4. I've already written a fuse module for sftp.
>
> I've seen the example nfs4-cat.c to follow.
>

Ah I see.
Sorry for misunderstanding.

An NFSv4 fuse module would require quite a lot of work, but it should not
be hard work.
This is mainly because NFSv4 support in libnfs only exists for the low
level raw RPC interface
and nothing is supported yet in the nice high-level vfs interface such as
nfs_open() and friends.

But it should not be too hard to work with the raw RPC API. Tedious
certainly but not too hard.


One thing to be aware of for NFSv4 is that it is normally a bi-directional
protocol, where the server will do callbacks
back to the client for certain events as expiring delegations and such.
That part might be difficult to implement for a ssh-port-forwarding style
implementation.

nfs4-cat.c does set up a callback function for this just for completeness
of the example.
nfs4-cat.c does however never do any locking or delegation, yet, which
means that in that example
the callback interface will actually never be used.

For your use case, I think you can get away with completely skipping
setting up a callback port
as long as you do not use locking/delegations/... or anything else that
actually requires callbacks in NFSv4.
That might make things a tiny bit easier.


ronnie sahlberg

**Comment by sahlberg** [comment]
Looking at nfs4-cat.c
Instead of using this to connect to the server :

if (rpc_connect_program_async(client.rpc, url->server,
NFS4_PROGRAM, NFS_V4,
connect_cb, &client) != 0) {
fprintf(stderr, "Failed to start connection\n");
exit(10);
}

you should use something like
if (rpc_connect_async(rpc, server, 2049, rpc_connect_program_1_cb, data) !=
0) {
rpc_set_error(rpc, "Failed to start connection");
free_rpc_cb_data(data);
return -1;

The first example, from nfs4-cat.c will use portmapper and thus first
connect to port 111 before it connects to port 2049 for nfs.
The second example will establish a tcp connection directly to port 2049
and skip the portmapper stage.

That way you only need to portforward a single port instead of two ports.

**Comment by stefbon** [comment]
Thanks a lot for the info.
The connection from server back to client to do calls like delegations is not yet necessary.
It has my interest cause locking is one of the things I want to work.
And delegations? I know the kernel nfs4 client module does support them but when are these "called".
But this connection may also be useful for fs change notify, which I want to make work for fuse. I've got patches to make inotify work with fuse, but I've set them in the freezer.

The way my program works is that services on hosts on the network are detected with avahi. This results in an address and a port. This way I can make my program connect directly without using the portmapper stage.

Stef

**Comment by sahlberg** [comment]
On Wed, Mar 1, 2017 at 5:10 AM, stefbon <notifications@github.com> wrote:

> Thanks a lot for the info.
> The connection from server back to client to do calls like delegations is
> not yet necessary.
> It has my interest cause locking is one of the things I want to work.
> And delegations? I know the kernel nfs4 client module does support them
> but when are these "called".
>
The delegations are there to make it possible to do client side caching
safely.
This is for both read/read-ahead caching as well as write-back caching on
the client.

Just like oplocks in the cifs world, when a delegation is
recalled/cancelled from the server side
this is a signal that any read-cache/page-cache should be invalidated.
For the write-back cache case it is a signal that any cache and dirty pages
should be destaged right away.


I am not sure/have no idea if fuse does any caching internally or if the
page-cache does for fuse filesystems.
If either of them do, then it might be an idea to try to get the plumbing
done to propagate the delegation stuff
so that things are destaged at the right time and caches are dropped at the
right time.



But this connection may also be useful for fs change notify, which I want
> to make work for fuse. I've got patches to make inotify work with fuse, but
> I've set them in the freezer.
>
Yupp, notify needs these too.


> The way my program works is that services on hosts on the network are
> detected with avahi. This results in an address and a port. This way I can
> make my program connect directly without using the portmapper stage.
>
Ah, ok.

**Comment by stefbon** [comment]
>The delegations are there to make it possible to do client side caching
>safely.
>This is for both read/read-ahead caching as well as write-back caching on
>the client.

Ok, how are these initiated? Does the client? I do not know any call by fcntl for example where the client wants a delegation.

And yes fuse has the ability to read from cached pages. The open call reply has a flag to tell the kernel to use the cache or not.

As fuse programmer you can make use of this by testing the mtime, or something simular.

Stef

**Comment by sahlberg** [comment]
On Thu, Mar 2, 2017 at 3:15 AM, stefbon <notifications@github.com> wrote:

> The delegations are there to make it possible to do client side caching
> safely.
> This is for both read/read-ahead caching as well as write-back caching on
> the client.
>
> Ok, how are these initiated? Does the client? I do not know any call by
> fcntl for example where the client wants a delegation.
>

Yeah, these are initiated by the client, during open().

See https://www.ietf.org/rfc/rfc3530.txt
section 9.4   and 14.2.16   (and a lot of other places)


And yes fuse has the ability to read from cached pages. The open call reply
> has a flag to tell the kernel to use the cache or not.
>
As fuse programmer you can make use of this by testing the mtime, or

**Comment by sahlberg** [comment]
I am not sure there is anything more to do here on the libnfs side
