### ISSUE TITLE
Howto do security?

### ISSUE THREAD

**Issue by stefbon** [sahlberg/libnfs#180]
Hi,

I use libnfs for my fuse fs to access nfs servers (nfs4).
Ready is the setup of a connection, callback, send of clientid,
confirm of clientid and rootfh.

I've got a question

a. how do I implement the security? When having the root fh, I have to
use the secinfo call.
And then?

I do not have experience with the rpcsec_gss. I guess I have to use a
external library for that.

Stef

**Comment by sahlberg** [comment]
NFS security is done using RPC-GSS and Kerberos.

For NFS it is fairly rare that this is used due to the administrative overhead to set up and maintain
both a KDC as well as all the other required infrastructure that Kerberos needs :-(
This means that for most people/sites it is just not justified due to the effort required.

I have no plans to add GSS + KRB5 support to libnfs at this stage since none of my use cases really need it.


If you want to try adding it, then go for it. It will be a fair amount of work and low level plumbing inside libnfs.
In particular in the zdr part of the library as GSS happens in the lower ONC-RPC layer and not the NFS layer.

You would need to use the MIT Kerberos packages as they contain both Kerberos itself as well as GSS-API and wrappers. There are also a few RFCs that describe how to do GSS with ONC-RPC that could help.
