### ISSUE TITLE
ganesha

### ISSUE THREAD

**Issue by observer1** [sahlberg/libnfs#188]
Hi
I'm seeing this error with a nfs-ganesha server

libnfs error: server max rsize of 67108864 is greater than libnfs supported 1048576 bytes

Can you help me with this?

Thanks

**Comment by sahlberg** [comment]
Ouch, that is silly of me to error out just because the server supports huge io sizes.
Better is to just clamp the max io size we return to the app to the max that libnfs currently supports.

This should be fixed in commit a523f843530d05b40353244709bdcf9fd5cd4d96
If you can test and verify this fixes this issue would be awesome.

I am planning a new release of the library for next week, so it would be nice to make sure this bug is properly fixed before then.

Thanks for your bugreport!

**Comment by observer1** [comment]
I will try to test if have enough time, thanks!!

**Comment by sahlberg** [comment]
Verified. Closing.

**Comment by observer1** [comment]
I tested the change and it seems to be alright but it doesn't seem to be on the latest release.
Could it be included please?
