### ISSUE TITLE
Provide a way to disable autoreconnect

### ISSUE THREAD

**Issue by earlchew** [sahlberg/libnfs#212]
As a application user, I want to be able to disable autoreconnect so that I can reconnect my NFS client to another IP address in my storage cluster. With autoreconnect enabled, the NFS client tries to reconnect to an IP address that it no longer available.

**Comment by sahlberg** [comment]
I see.
You basically want to have libnfs fail fast so that you can reconnect to a
different server ip instead of having to wait for the reconnection logic to
try and fail 10 consecutive tcp connection attempts (which may be a long
time).
That is a far use-case but I think we need more than this patch.

For the current use-case where we just try to reconnect back to the same
server, we still need to do some additional work in order to be able to
re-issue the PDUs that are in flight.
See rpc_reconnect_requeue().
We need to both re-set the number of bytes sent counter for the current pdu
as we might have just sent partial data to the server when the network
disconnect happen.
We also need to move any of the pdus in the different waitpdu buckets back
to the outqueue so that they will eventually be re-sent to the server once
the connection is recovered.
Otherwise we will drop all the pdus that were in flight during the network
session failure, which is not what we want.


So what I think you want instead is probably something almost like the
current rpc_reconnect_requeue() but switch the rpc sock_addr before you
invoke.


I think something like this :
1, Set reconnect attempts to 0.

2, once the connection fails you will notice this immediately by
rpc_service() returning an error.
3, in your app you now update the rpc structure to point to a different
sock_addr for the server you failed over to.
4, Set reconnect attempts to something sane, like 3 or so
5, once you are confident the new server is available, then invoke
rpc_reconnect_requeue() directly from you app
and hopefully it will now do all its goodness. Re-queue any pdus that are
in flight, and reconnect to the new target you swapped to.

6, once connected successfully, maybe set reconnect attempts back to 0
again?

**Comment by sahlberg** [comment]
Maybe an even better, and a lot less intrusive change,  would be to add
code so you can register a "reconnect handler" to the rpc structure.
Then have rpc_reconnect_requeue() just invoke that handler before every try
to reconnect.

The flow would then be something like :

1, In your app, once the rpc/nfs context is created, register a function
pointer to your own reconnect handler :
     rpc_set_reconnect_handler(rpc, void *reconnect_handler(struct
rpc_context *rpc))


2, When the connection has failed, have rpc_reconnect_requeue() call out to
your handler
    if (rpc->rpc_reconnect_handler) {
          rpc->rpc_reconnect_handler(rpc);
    }

3, In your handler, update the rpc socket address for the server to the new
ip. then return to rpc_reconnect_requeue()

4, rpc_reconnect_requeue() re-queues all the pdus and tries to reconnect to
the new target. All is good and no pdus are dropped and no data is lost.

**Comment by earlchew** [comment]
@sahlberg At present, for this use case, the approach I've taken does not attempt to be very clever, or take advantage of any of the strategies that you have outlined. It counts on the fact that this scenario happens rarely (or should happen rarely), and when it occurs, the entire NFS client connection is torn down. Because there are no retries, the tear down should occur very soon after the error is detected.

Of course this means that all inflight requests are discarded, and must be rescheduled by the application. IO that has not yet been acknowledged (no callback issued indicating success) is not regarded as durable.

This is not to say that the strategies you outline are not useful, only that the use case I have would not make use of them.

**Comment by sahlberg** [comment]
Ok,

If you are willing to do any data integrity guarantees from within your
application itself then I am fine with this patch.
Please add an update to the URL format in README as well as libnfs.h to
document this argument and mention that
any commands in flight are lost on session failure. And I will merge it.
