### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by cholcombe973** [sahlberg/libnfs#266]
I was wondering what kind of safety guarantees this library provides for the nfs context.  Is it safe to share between threads?  I don't remember reading this in the header file docs so I thought it's worth asking.  I'm writing bindings for libnfs in rust and I wanted to make sure I don't have any threading related memory leaks.

**Comment by sahlberg** [comment]
Libnfs is not threads safe. It is designed to be async/event driven instead.

The things that prevent is from being thread safe is mainly the list handling (adding/removeing PDUs from the out and the wait list) and that nfs_service() can never be called concurrently.

If you absolutely need to use it in a multithreaded application instead of an async/event driven application you can protect the entrypoints to libnfs by two mutexes and make it safe.

This patch from a different project shows how to wrap all libnfs safely inside mutexes : 
https://github.com/sahlberg/fuse-nfs/commit/4b5687095493e68c6c7301a94a2d13384a51dcef
