### ISSUE TITLE
Permission denied on Android

### ISSUE THREAD

**Issue by personshelldon** [sahlberg/libnfs#290]
Hello! I'm trying to test this lib on Android and I can not get it to work as expected. I built it without any problems, and I pushed `nfs-ls` to `system/bin/` for test. If I run it as a regular user or a system user I always get `Failed to mount nfs share : mount_cb: RPC error: Mount failed with error MNT3ERR_ACCES(13) Permission denied(13)`, but if I run `nfs-ls` as a root user - everything works on the same server and path as expected. 

Is there any workaround for this issue for Android? I want get it to work without any usage of root on the device. If root exists, I already implemented the solution that works via `mount` command. 
Thanks in advance.

**Comment by lampovo** [comment]
It's all because mount is under user privilege.
If you want to change it (and you want), you can go to file **libnfs-zdr.c** and change this code:
libnfs_authunix_create("libnfs", **getuid()**, **getgid()**, 0, NULL);

for example set uid and gid to NULL.

**Comment by sahlberg** [comment]
NFS servers traditionally only allow connections from client ports <= 1024
(because that means the process on the client runs as root, and that is how security worked in the mid 1980s :-)

You can fix this by either adding the "insecure" export option for the share in /etc/exports on the server, or by setting the appropriate capability on the androind app to allow opening client ports <= 1024 :+1: 
    sudo setcap 'cap_net_bind_service=+ep' /path/to/executable

Unfortunately, when I looked into it it did not seem possible to do cap_net_bind_service on android :-(

so insecure in /etc/exports is your only option. Sorry.
