### ISSUE TITLE
How can I create many nfs TCP connections to one server with just one client?

### ISSUE THREAD

**Issue by AlexKingGo** [sahlberg/libnfs#291]
Hi , sahlberg.
   Sorry to bother you. I want simulate that many clients mount on one server, there should be many TCP connections, but  I have just one client node, so this mean the only one client need create and hold many TCP connection with the server. However, there is only one TCP connection between the client and server when I mount different path with shell or other test suite.
    Could you please answer my two questions?
     1. How can I create a new TCP connection between the only one client and server for each Mount?
     2. If  the question 1 can be implemented, from which parts of the libnfs I can benefit ? I mean, parts can implement question 1.

Best wish for you

**Comment by sahlberg** [comment]
On Thu, Jun 20, 2019 at 2:03 AM AlexKingGo <notifications@github.com> wrote:

> Hi , sahlberg.
> Sorry to bother you. I want simulate that many clients mount on one
> server, there should be many TCP connections, but I have just one client
> node, so this mean the only one client need create and hold many TCP
> connection with the server. However, there is only one TCP connection
> between the client and server when I mount different path with shell or
> other test suite.
> Could you please answer my two questions?
> 1. How can I create a new TCP connection between the only one client and
> server for each Mount?
> 2. If the question 1 can be implemented, from which parts of the libnfs I
> can benefit ? I mean, parts can implement question 1.
>
That should be fairly easy to do.
Note that while each nfs_context only has one single TCP connection, you
can easily create
many separate nfs_context's and multiplex between them.

Each nfs_context will have its own tcp connection to the server.

You would need to use the async interface in order to be able to do many
concurrent I/O from many different contexts concurrently.


If you want each to "pretend" to be a different client and come from a
different hostname, when creating the contexts bug before connecting them,
you can use
struct AUTH *libnfs_authunix_create(const char *host, uint32_t uid,
uint32_t gid, uint32_t len, uint32_t *groups)
and set a different client hostname for each connection.
This is the credentials field that goues in the RPC layer and it contains
the UID/GID/other-groups as well as the clietn hostname.
Most/all servers probably completely ignore the client hostname however but
it might still be useful to set it to make it easier to look at traces in
wireshark.
It shoudl be free form ASCII text so you could set it to "Client #xxx"


regards
ronnie sahlberg

**Comment by sahlberg** [comment]
Solution provided. Closing.
