### ISSUE TITLE
I am not able to find any API for corresponding to nfs4_getfacl and nfs4_setfacl

### ISSUE THREAD

**Issue by akhilsvaidya** [sahlberg/libnfs#346]
I am not able to find any API for corresponding to nfs4_getfacl and nfs4_setfacl. Is nfs4 ACL APIs available in libnfs?

**Comment by sahlberg** [comment]
No the upper layer function is not implemented yet.
It should be fairly straightforward to add since all the RPC and XDR layer is there already and I think it would mostly be calling the existing getattr function but for attribute #12. (after 5 seconds of causual looking at nfs4.x)

The same is true for NFSv3 ACLs, the RPC and XDR is there but not exposed to an upper layer function.


Do you want to have a go at adding a higher layer wrapper for these RPC calls so we get get/set facl support?

**Comment by bishnu1184** [comment]
@sahlberg Can you please share some sample code to read ACL details  ?

**Comment by sahlberg** [comment]
See nfs_v4.c   the function you need to use is nfs4_op_getattr() and the attribute you need to ask for is #12, FATTR4_ACL.

**Comment by bishnu1184** [comment]
Thanks @sahlberg for your reply.
Sorry I may sound very naive, But I looked into nfs_v4.c and it look like I will have to copy quite a few structures locally to use that, as well as I could not completely comprehend how will I receive ACL structure using that. 
Meantime I also came across one example of ACL in https://github.com/sahlberg/libnfs/blob/master/examples/nfsclient-raw.c Can you please let me know if I can use same approach as in above link for my purpose ? or there will be any limitations using above approach using GETACL3args and rpc_nfsacl_getacl_async()

Thanks,
Bishnu

**Comment by bishnu1184** [comment]
@sahlberg I could fetch ACL details using method shown in https://github.com/sahlberg/libnfs/blob/master/examples/nfsclient-raw.c, but ACL returned as GETACL3res structure don't have detail in user friendly way like instead of user name I get UID.
I looked into function nfs4_op_getattr() and attribute FATTR4_ACL, which you suggested, but I could not understand, how will I receive fattr4_acl structure in callback using nfs4_op_getattr() function, also I am facing compilation related issues with Visual Studio 2015 when I am trying to use local structures defined in nfs_v4.c. Can you please share bit more detail about steps using which I can get the ACLs

**Comment by sahlberg** [comment]
Take a look at current master.
I have pushed support to read the nfsv4 acl.
See nfs-io for an example.

**Comment by sahlberg** [comment]
NFS only uses uid/gid in the protocol, not names.
Mapping to names are outside the scope of NFS because there is no standard way of doing this and the methods differs from site to site.
More popular methods are "shared passwd files" for small sites, or YP/NIS   or LDAP or even active directory being popular for larger sites.

So for usermapping you will have to find out how it is implemented in your environment and do it outside of libnfs.

**Comment by bishnu1184** [comment]
Thanks for ACL support.
I tested with latest code and I could get NFSv4 ACL (except 'flag' value is always coming as 0 only not sure if this is correct).
Right now you have added ACL related functions at last of "nfs4_getacl_async.h" outside of "extern C" block. That causes linking issue when I try to call these functions from .CPP files (because of C++ name mangling). Is it possible to declare these functions inside "extern C" block like other functions ?

**Comment by sahlberg** [comment]
I have tweaked the headerfile for c++ and pushed.
The flags will normally be set to 0 on most nfs4 servers.
Have you checked if the server actually sends a non-0 value here?

**Comment by sahlberg** [comment]
Done.

**Comment by bishnu1184** [comment]
Sorry for not replying earlier, got busy with some other stuff.
Yes, thanks after your fix C++ code is working fine now. 
I am not sure how to check the value sent by the server. 

I have one question, is there any support for ACL in NFSv3 and what was the ACL shown in https://github.com/sahlberg/libnfs/blob/master/examples/nfsclient-raw.c this example Is this for NFSv3? 
Because I don't see any ACL detail in NFSv3 RFC document.

**Comment by sahlberg** [comment]
On Fri, Jul 23, 2021 at 2:36 PM bishnu1184 ***@***.***> wrote:

> Sorry for not replying earlier, got busy with some other stuff.
> Yes, thanks after your fix C++ code is working fine now.
> I am not sure how to check the value sent by the server.
>
> I have one question, is there any support for ACL in NFSv3 and what was
> the ACL shown in
> https://github.com/sahlberg/libnfs/blob/master/examples/nfsclient-raw.c
> this example Is this for NFSv3?
> Because I don't see any ACL detail in NFSv3 RFC document.
>

NFSv3 ACL is not part of the NFS protocol but runs as a separate protocol
on the same socket as the nfs server.
As far as I know virtually all NFSv3 servers also support the NFSACL
protocol.

NFSACL was never published as an RPC but became a defacto standard anyway.
You can see the definitions for this protocol in nfs/nfs.x

**Comment by sahlberg** [comment]
For an example,  update SERVER and EXPORT in nfsclient-raw.c and just run
it under wireshark and you will see examples of the GETACL method.

**Comment by bishnu1184** [comment]
Okay, I will test and let you know.

**Comment by GuruprasadUjwal** [comment]
This is very helpful, thanks.
Are you adding v4 setacl. if not then pls  tell me the changes pending for v4 setacl. I will try.
