### ISSUE TITLE
Optimizing file access by caching fh3 structs

### ISSUE THREAD

**Issue by santagada** [sahlberg/libnfs#366]
Hi,

I've been trying to optimize nfs access by caching fh3 results for folders to speed up lookups. As I see right now there's no place to add a cache for those in the libnfs code is there? The way I would implement it would also need to be thread safe and shared on all threads (I have one nfs contex/connection/socket per thread). Is anything like that planned? Anyone ever thought of adding it?

**Comment by sahlberg** [comment]
On Mon, Oct 11, 2021 at 11:03 PM Leonardo Santagada <
***@***.***> wrote:

> Hi,
>
> I've been trying to optimize nfs access by caching fh3 results for folders
> to speed up lookups. As I see right now there's no place to add a cache for
> those in the libnfs code is there? The way I would implement it would also
> need to be thread safe and shared on all threads (I have one nfs
> contex/connection/socket per thread). Is anything like that planned? Anyone
> ever thought of adding it?
>

It is hard to do this type of caching safely for NFSv3 since there are no
leases or cache coherency protocol.
What some clients do is to cache things for, say up to a second by default,
and hope for the best.  But it is unsafe.

I don't have any immediatel plans for this but it might be worthwhile as an
optional feature for some workloads.

On the topic of multithreading,   please see the pthread branch.
It is a wip implementation to make libnfs multithread safe so that you can
use a single context and use it across many/all your threads.
Don;t use it on production data just yet, but please try it out if you are
interested.

**Comment by santagada** [comment]
oh I thought the fh3 structures were opaque but guaranteed stable (with the caveat that it was the folder at that path in the past).

we are on windows so if this is pthread specific it won't work (and we want to move to production data, so I think well first go with 4.0.0).

Any chance to be able to plug our own memory manager? I see that a lot of the functions do malloc by themselves so it would have been nice to plug our memory manager (we are using jemalloc).

**Comment by sahlberg** [comment]
Thinking about it more.
This is what you can do.

First, path lookups, like in open() is very expensive in NFS because the
protocol does not handle paths.
So anything that handles a path will decompose to being a sequence of
LOOKUPs one component at a time until you reach the target.
Or sometimes you have a combination of LOOKUP+GETATTR.

(LOOKUP may return the attributes of the object, thus making the GETATTR
redundant but there is no guarantee,
lets assume it does return the attributes for now)

This means that looking up a path takes one roundtrip for each path
component, or two roundtrips per component if you have to do
an explicit GETATTR to find the attributes.
Similarly, if a client needs to validate cached handles/attributes for a
path, then usually
the client would issue a sequence of GETATTR, one for each cached component
and check that the mtime has not changed.
If mtime has changed you have to discard the caches and re-lookup the
target and all intermediate directories.


What you could do in libnfs safely, since we have a powerful async
interface available, is to reduce this to just a single roundtrip
regardless of how deep the path is.
To do this, what you need to do is
1, for all directories, add a cache for all discovered direntries
(discovered by LOOKUP or READDIRPLUS)
where you store the filehandle as well as the attributes, keyed by the
component name.
2, For all the path-based commands, like nfs3_open_async(),  normalize the
path and then check IF you have cached entries for
every single component in the path.
If you do, then you can:
2.1: for each component, send an async LOOKUP of the component in its
parent handle.
2.2: for each reply received, validate that the LOOKUP was successful. I.e.
the name exists, the filehandle matches the cached value and the mtime is
unchanged.
2.3: once all replies are received, if all the tests in 2.1 were
suuccessful then you can use the cached handle.

The trick here is that using the async interface you can do 2.1 - 2.3
completely in parallell for all the components in the path.
This approach would allow you to safely validate and use a cached
filehandle after spending just one roundtrip to validate the entire path.
There would be a pretty decent amount of work to implement this but it
would work and it would speed up handling of deep paths.

**Comment by santagada** [comment]
it all makes sense, just the amount of data you need to cache is huge, as these fh3 are up to 64 bytes long (and in libnfs there's an int for the size as well).

in our particular use cases folders never move around so I'll do a simple cached_open function that will cache the last folder to files and that will be enough for us. Also only storing a murmurhash of the path instead of actual strings to make this a uniform sized hashmap.

knowing about ESTALE will help a lot, thanks for sharing all of this. (and thanks again for the lib, implementing nfs from scratch would have been very painful).

**Comment by sahlberg** [comment]
On Wed, Oct 13, 2021 at 7:11 PM Leonardo Santagada ***@***.***>
wrote:

> it all makes sense, just the amount of data you need to cache is huge, as
> these fh3 are up to 64 bytes long (and in libnfs there's an int for the
> size as well).
>
> in our particular use cases folders never move around so I'll do a simple
> cached_open function that will cache the last folder to files and that will
> be enough for us. Also only storing a murmurhash of the path instead of
> actual strings to make this a uniform sized hashmap.
>
> knowing about ESTALE will help a lot, thanks for sharing all of this. (and
> thanks again for the lib, implementing nfs from scratch would have been
> very painful).
>

Sounds good. That use case is too specialized so it would not be a good fit
in the library but the application should be able to deal with it outside
of the library.
Just, I would avoid using a hash as a replacement for the actual path.
One day, sooner or later, you may win the lottery and encounter a hash
collission and everything will become sad.
