### ISSUE TITLE
XBMC cant not access bind mounted directories.

### ISSUE THREAD

**Issue by Kerwood** [sahlberg/libnfs#37]
Hi.. Im having an issue, and i think it relates to libnfs.

Im trying to setup my NFS mounts the NFSv4 way, with only one exported folder and the others, that I want to share, bind mounted into the exported folder.

See link for more details. http://forum.xbmc.org/showthread.php?tid=176446

Is this not supported in libnfs or am i doing it wrong?

Thank you very much for your time and effort on this project.

**Comment by sahlberg** [comment]
Blast from the past ...

If you are interested in trying out NFSv3 in libnfs again,

I have added code to libnfs to automatically track all nested submounts and automatically switch beteen then so that the application does not have to care about mounts.

The way it does it is by fetching a list of all mounts from the server during mount time and then build a mapping between the relative path between mounts and their associated filehandles and nfs attribute structures.
Once you try to access a directory that is a submount, libnfs will then internally subsistute your path with the path to the nested mount.

In order to make this work, you would still need to export both the parent and all the nested mounts from the server:

So if you have /data   and then under /data you have two other filesystems foo and bar you would have to export all three of
/data
/data/foo and
/data/bar

But, on the libnfs/xbmc/kodi side, you now only need to mount/use   /data
and libnfs will internally take care of that /data/foo and /data/bar are actually different filesystems.



It is only available in the current master branch,  but I intend to release this as a new version in a few weeks if all goes well.
