### ISSUE TITLE
v5.0.1 multithreadig not thread safety

### ISSUE THREAD

**Issue by rjlee0** [sahlberg/libnfs#388]
I found at least these places:
1. nfs_v3.c, line 4959, nfs3_pread_async_internal: 'rpc_nfs3_read_async' and 'data->num_calls++' thread unsafe. nfs3_pread_mcb may be called in other threads before 'num_calls++'
2. 'num_calls++' and  'num_calls--' also thread unsafe

**Comment by sahlberg** [comment]
increment of integers should be atomic instructions on all modern cpus  so should be threadsafe.

**Comment by sahlberg** [comment]
Thankyou. I did not  know that.   CPUs are more complex nowadays than I thought.
I have protected these with a simple mutex for now and will keep this in mind.

**Comment by sahlberg** [comment]
Please have a look at this.
I use stdatomic when available and a mutex when not.

https://github.com/sahlberg/libnfs/commit/ac88db3ddabf2553f88ebd53c6e10a0eca37a5f8

**Comment by Daniel-Abrecht** [comment]
I think it looks mostly fine. Although, I'm not really an expert on these things. Last time I had to do refcounting, I essentially just did it the same way chromium did it (https://chromium.googlesource.com/chromium/src/base/+/refs/heads/main/atomic_ref_count.h#19).

They seam to use `memory_order_acq_rel` for decrement, although I don't think this is necessary here, because you aren't using the result, so `memory_order_relaxed` is probably fine.

But you do have a few places where you check if `num_calls` is 0. I'd use `atomic_load_explicit` with `memory_order_acquire` in those places.
