### ISSUE TITLE
nfs4 open with share_deny modes?

### ISSUE THREAD

**Issue by stsp** [sahlberg/libnfs#421]
Hi.

It seems the raw API supports nfs4
"share reservation" modes. But I can't
find the high-level open() API that exports
that feature. It seems nfs4_populate_open()
just always uses `OPEN4_SHARE_DENY_NONE`.

How difficult would it be to add the new
open() variation that takes the share deny
mode?

**Comment by sahlberg** [comment]
It probably wouldn't be hard from a technical standpoint but how would it  work and how would it be defined?

The high level API is meant to mimic the posix api where things like sharemodes just does not exist.
I am not sure about how useful a extended posix+plus-other-things API would be since where do you draw the line on what is posix api and what is nfsv4 api?

I think the best solution is to keep the posix api as close as posix as possible. Then when you need to go outside of posix
you can still do that you just have to convert the nfs context into an rpc context and call the raw nfsv4 api directly.

Or maybe add a nfs4_open_ex() function that makes it clear it is not even trying to be posix but offers direct access to nfsv4 specific features.

**Comment by stsp** [comment]
> Or maybe add a nfs4_open_ex() function that makes it clear it is not even trying to be posix
> but offers direct access to nfsv4 specific features.

Yes, something like this would be great.
"share reservations" is windows-specific,
so maybe it makes sense, along with
posix-alike API, to provide also windows-alike
API in the areas where nfs4 offers the
windows-specific extensions?
