### ISSUE TITLE
malloc() can return NULL in OOM conditions, resulting in a NULL dereference whilst trying to create an error string

### ISSUE THREAD

**Issue by midnightveil** [sahlberg/libnfs#434]
See linked code below.

https://github.com/sahlberg/libnfs/blob/b759d4ca7186253c03315a876353dcd8ef3e10bc/lib/init.c#L314-L318

**Comment by sahlberg** [comment]
On this one we can just check for NULL and return immediately and hope for the best.
Bunch of embedded systems use the library and it may be difficult to restart those when if they fail,
now if it is a true oom situation the apps will likely eventually crash the system anyways
but if at least it does not crash due to libnfs then that is good.

**Comment by sahlberg** [comment]
checked in a small fix.

**Comment by linuxsmiths** [comment]
> On this one we can just check for NULL and return immediately and hope for the best. Bunch of embedded systems use the library and it may be difficult to restart those when if they fail, now if it is a true oom situation the apps will likely eventually crash the system anyways but if at least it does not crash due to libnfs then that is good.

Since the function in question doesn't have a way to convey error status to the caller, I feel silently swallowing the error can result in confusion where things will not work (due to memory issue) and there won't be proper error conveyed.

**Comment by sahlberg** [comment]
On Thu, 2 May 2024 at 14:04, linuxsmiths ***@***.***> wrote:

> On this one we can just check for NULL and return immediately and hope for
> the best. Bunch of embedded systems use the library and it may be difficult
> to restart those when if they fail, now if it is a true oom situation the
> apps will likely eventually crash the system anyways but if at least it
> does not crash due to libnfs then that is good.
>
> Since the function in question doesn't have a way to convey error status
> to the caller, I feel silently swallowing the error can result in confusion
> where things will not work (due to memory issue) and there won't be proper
> error conveyed.
>

For this case we could just return a statically allocated string "out of
memory". It will likely be correct because if rpc_set_error() failed
then it is highly probable that what caused the original error and caused
rpc_set_error() to be called was also an oom situation.
I will do a small patch for that and return a static string instead of
NULL.
