### ISSUE TITLE
Have we tested TCP_NODELAY option with RPC connections?

### ISSUE THREAD

**Issue by linuxsmiths** [sahlberg/libnfs#481]
With limited testing I've found that turning nagle off on RPC connections seem to help the throughput in some cases (tried with read).
@sahlberg, have you explored/tested that in the past? If not, I would suggest we enable it after decent validation testing.

**Comment by sahlberg** [comment]
I haven't tested it.   I didn't expect the lack of TCP_NODELAY  would have much effect unless on a mostly idle connection
but.

Libnfs already collects all the data that needs to be sent into an iovector and sends it all out in a single writev() call
so TCP_NODELAY should be fine.

There are some embedded platforms that don't have writev() and instead emulate it by a loop of write() commands. Those platforms would hurt a little due to the extra cpu utilization due to the many more segments that would need to send.
(one segment for the recordmarker, one segment for the rpc header, one for the nfs header, one for the nfs payload, plus one for the potential padding).
Those platforms are not really high-performance anyway so it should be fine.

I don't thing we need an api to enable/disable TCP_NODELAY, we can just set it unconditionally when the socket is created IFF TCP_NODELAY is defined.
Some platforms don't have TCP_NODELAY so please add a check to autoconf and cmake for it and set it inside a
#ifdef TCP_NODELAY  block.

**Comment by sahlberg** [comment]
As there are no drawbacks for using TCP_NODELAY in libnfs I have pushed a change to master that sets it unconditionally
every time a tcp socket is created.
